import { useState } from 'react';
import { Link,NavLink,useNavigate } from 'react-router-dom';
import { useAuth } from '../AuthContext.jsx';
import { LanguageSwitcher,useI18n } from '../i18n/I18nContext.jsx';
import CompanyLogo from './CompanyLogo.jsx';

function NavIcon({name}){const paths={home:<><path d="M3 10.5 12 3l9 7.5"/><path d="M5.5 9.5V21h13V9.5M9 21v-7h6v7"/></>,contacts:<><path d="M16 20v-1.5a4.5 4.5 0 0 0-4.5-4.5h-4A4.5 4.5 0 0 0 3 18.5V20"/><circle cx="9.5" cy="7" r="4"/><path d="M17 11a3.5 3.5 0 0 1 4 3.5V16M16.5 3.6a3.5 3.5 0 0 1 0 6.8"/></>,profile:<><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></>};return <svg className="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}

export default function AppShell({title,eyebrow,children}){const{user,logout}=useAuth();const{t}=useI18n();const navigate=useNavigate();const[loggingOut,setLoggingOut]=useState(false);const[logoutError,setLogoutError]=useState('');const navigation=[['/dashboard','nav.home','home'],['/contacts','nav.contacts','contacts'],['/profile','nav.profile','profile']];async function signOut(){if(loggingOut)return;setLoggingOut(true);setLogoutError('');try{await logout();navigate('/login',{replace:true})}catch{setLogoutError(t('session.logoutError'));setLoggingOut(false)}}const links=navigation.map(([to,key,icon])=><NavLink key={to} to={to} end={to==='/dashboard'}><NavIcon name={icon}/><span>{t(key)}</span></NavLink>);return <div className="app-layout"><aside className="app-sidebar"><Link className="brand-lockup" to="/dashboard"><span className="brand-mark">N</span><span>NFC Connect<small>{t('brand.matching')}</small></span></Link><nav aria-label={t('nav.exhibitor')}>{links}</nav><LanguageSwitcher/><div className="sidebar-user"><span className="avatar">{user?.fullName?.charAt(0)?.toUpperCase()||user?.username?.charAt(0)?.toUpperCase()||'U'}</span><div><strong>{user?.fullName||user?.username}</strong><small>{t('common.exhibitor')}</small></div></div>{logoutError&&<small className="sidebar-error" role="alert">{logoutError}</small>}<button className="sidebar-logout" type="button" onClick={signOut} disabled={loggingOut}>{t(loggingOut?'common.loggingOut':'common.logout')}</button></aside><main className="app-main"><header className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div><div className="page-header-tools"><span className="event-chip">{t('brand.connected')}</span><LanguageSwitcher className="mobile-language"/></div></header>{children}</main><nav className="bottom-nav" aria-label={t('nav.mobileExhibitor')}>{links}</nav></div>}
export function CompanyAvatar({company,large=false}){return <CompanyLogo logoUrl={company.logo_url} companyName={company.company_name} size={large?'large':'medium'} className="company-avatar"/>}
export function EmptyState({title,children}){return <section className="empty-state-card"><span className="empty-icon" aria-hidden="true">◇</span><h2>{title}</h2>{children&&<p>{children}</p>}</section>}
export function LoadingState({children}){const{t}=useI18n();return <div className="loading-card" role="status"><span className="spinner" aria-hidden="true"/>{children||t('common.loading')}</div>}
export function ErrorState({children}){const{t}=useI18n();return <div className="error-message" role="alert">{children||t('common.error')}</div>}
