import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { deactivateAdminCompany, getAdminCompanies } from '../api.js';
import AdminHeader from '../components/AdminHeader.jsx';
import { EmptyState, ErrorState, LoadingState } from '../components/AppShell.jsx';
import CompanyImportPanel from '../components/CompanyImportPanel.jsx';
import CompanyLogo from '../components/CompanyLogo.jsx';
import { useAuth } from '../AuthContext.jsx';

export default function AdminCompaniesPage() {
  const { csrfToken } = useAuth();
  const [companies, setCompanies] = useState([]); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(''); const [query, setQuery] = useState('');
  const [copied, setCopied] = useState(null); const [showImport, setShowImport] = useState(false);
  const visible = useMemo(() => companies.filter((company) => `${company.company_name} ${company.company_code}`.toLowerCase().includes(query.trim().toLowerCase())), [companies, query]);
  const nfcUrl = (tag) => `${window.location.origin}/company/${encodeURIComponent(tag.public_token)}`;
  async function load() { setError(''); try { const data = await getAdminCompanies(); setCompanies(data.companies); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function deactivate(company) { if (!window.confirm(`Deactivate ${company.company_name}?`)) return; try { await deactivateAdminCompany(company.id, csrfToken); await load(); } catch (e) { setError(e.message); } }
  async function copy(tag) { try { await navigator.clipboard.writeText(nfcUrl(tag)); setCopied(tag.id); window.setTimeout(() => setCopied(null), 1500); } catch { setError('Clipboard access was unavailable. You can open and copy the URL manually.'); } }
  return <div className="admin-page"><AdminHeader/><main className="admin-content"><div className="page-heading"><div><span className="eyebrow">Organizer</span><h1>Companies</h1><p>Manage participating businesses and their NFC profiles.</p></div><div className="page-actions"><button className="secondary-button" type="button" onClick={() => setShowImport(true)}>Import CSV / Excel</button><Link className="primary-link" to="/admin/companies/new">Add company</Link></div></div>{showImport && <CompanyImportPanel onClose={() => setShowImport(false)} onComplete={load}/>}<label className="search-input admin-search"><span aria-hidden="true">⌕</span><input aria-label="Search companies" placeholder="Search by name or code" value={query} onChange={(e) => setQuery(e.target.value)}/></label>{error && <ErrorState>{error}</ErrorState>}{loading ? <LoadingState>Loading companies…</LoadingState> : !visible.length ? <EmptyState title={query ? 'No matching companies' : 'No companies yet'}>{query ? 'Try another name or company code.' : 'Add the first company to create its NFC profile.'}</EmptyState> : <div className="visitor-grid">{visible.map((company) => <article className="visitor-card" key={company.id}><div className="visitor-heading"><div className="company-heading-identity"><CompanyLogo logoUrl={company.logo_url} companyName={company.company_name} size="small"/><div><h2>{company.company_name}</h2><span>{company.company_code}</span></div></div><span className={`badge ${company.is_active ? 'active' : 'inactive'}`}>{company.is_active ? 'Active' : 'Inactive'}</span></div><p className="confirmation-count"><strong>{company.confirmations}</strong> connection{Number(company.confirmations) === 1 ? '' : 's'}</p><div className="tag-list"><h3>NFC tags</h3>{company.nfc_tags.map((tag) => <div className="visitor-tag" key={tag.id}><div><strong>{tag.tag_code}</strong><code>{tag.public_token}</code><span className={`badge ${tag.is_active ? 'active' : 'inactive'}`}>{tag.is_active ? 'Active' : 'Inactive'}</span></div><div className="action-row"><a href={`/company/${encodeURIComponent(tag.public_token)}`} target="_blank" rel="noreferrer">View</a><button className="link-button" type="button" onClick={() => copy(tag)}>{copied === tag.id ? 'Copied' : 'Copy URL'}</button></div></div>)}{!company.nfc_tags.length && <p className="muted-note">No NFC tags assigned.</p>}</div><div className="action-row visitor-actions"><Link to={`/admin/companies/${company.id}/edit`}>Edit company</Link>{company.is_active && <button className="link-button danger" type="button" onClick={() => deactivate(company)}>Deactivate</button>}</div></article>)}</div>}</main></div>;
}
