import { useEffect,useRef,useState } from 'react';
import { Link,useNavigate,useParams } from 'react-router-dom';
import { confirmCompany,getPublicCompany } from '../api.js';
import { useAuth } from '../AuthContext.jsx';
import { CompanyAvatar } from '../components/AppShell.jsx';
import { LanguageSwitcher,useI18n } from '../i18n/I18nContext.jsx';
import '../i18n/production-refinement-translations.js';
import '../production-refinement.css';

function CompanyProfile({company,t}){return <article className="nfc-card"><header className="nfc-company"><CompanyAvatar company={company} large/><span className="eyebrow">{t('public.businessProfile')}</span><h1>{company.company_name}</h1><p className="meta">{[company.industry,company.country].filter(Boolean).join(' · ')||t('public.participant')}</p></header>{company.description&&<p className="description">{company.description}</p>}<dl className="profile-details">{company.contact_name&&<div><dt>{t('companies.contactPerson')}</dt><dd>{company.contact_name}{company.contact_position&&<small>{company.contact_position}</small>}</dd></div>}{company.email&&<div><dt>{t('common.email')}</dt><dd><a href={`mailto:${company.email}`}>{company.email}</a></dd></div>}{company.phone&&<div><dt>{t('common.phone')}</dt><dd><a href={`tel:${company.phone}`}>{company.phone}</a></dd></div>}{company.website&&<div><dt>{t('common.website')}</dt><dd><a href={company.website} target="_blank" rel="noreferrer">{company.website}</a></dd></div>}{company.address&&<div className="wide"><dt>{t('common.address')}</dt><dd>{company.address}</dd></div>}</dl></article>}

export default function PublicCompanyPage(){const{token}=useParams();const{user,loading:authLoading}=useAuth();const{t}=useI18n();const navigate=useNavigate();const[company,setCompany]=useState(null);const[confirmation,setConfirmation]=useState(null);const[loading,setLoading]=useState(true);const[loadError,setLoadError]=useState(false);const[phase,setPhase]=useState('idle');const[retry,setRetry]=useState(0);const attemptedRef=useRef(false);
useEffect(()=>{let live=true;attemptedRef.current=false;setLoading(true);setLoadError(false);setPhase('idle');getPublicCompany(token).then(data=>{if(live){setCompany(data.company);setConfirmation(data.confirmation)}}).catch(()=>live&&setLoadError(true)).finally(()=>live&&setLoading(false));return()=>{live=false}},[token]);
useEffect(()=>{if(loading||authLoading||!company||attemptedRef.current)return;if(!user){navigate(`/login?redirect=${encodeURIComponent(`/company/${token}`)}`,{replace:true});return}if(user.role!=='exhibitor'){setPhase('admin');return}if(confirmation){setPhase('already');return}attemptedRef.current=true;setPhase('connecting');confirmCompany(token).then(result=>{setConfirmation({confirmedAt:result.confirmedAt});setPhase(result.alreadyConfirmed?'already':'success')}).catch(()=>setPhase('error'))},[authLoading,company,confirmation,loading,navigate,retry,token,user]);
function tryAgain(){attemptedRef.current=false;setPhase('idle');setRetry(value=>value+1)}
const language=<LanguageSwitcher className="public-language"/>;
if(loading||authLoading)return <main className="nfc-page">{language}<section className="state-card auto-connect-state" role="status"><span className="spinner" aria-hidden="true"/><h1>{t('public.loading')}</h1></section></main>;
if(loadError||!company)return <main className="nfc-page">{language}<section className="state-card"><h1>{t('public.unavailable')}</h1><p>{t('public.inactive')}</p></section></main>;
if(phase==='admin')return <main className="nfc-page">{language}<CompanyProfile company={company} t={t}/></main>;
if(phase==='connecting'||phase==='idle')return <main className="nfc-page">{language}<section className="state-card auto-connect-state" role="status"><span className="spinner" aria-hidden="true"/><h1>{t('public.connecting')}</h1><p>{t('public.connectingBody',{name:company.company_name})}</p></section></main>;
if(phase==='error')return <main className="nfc-page">{language}<section className="state-card auto-connect-state" role="alert"><h1>{t('public.autoSaveError')}</h1><button className="primary-button" type="button" onClick={tryAgain}>{t('public.tryAgain')}</button></section></main>;
const already=phase==='already';return <main className="nfc-page">{language}<section className="state-card auto-connect-state"><span className="success-check" aria-hidden="true">✓</span><h1>{t(already?'public.already':'public.connectionSuccessful')}</h1><p>{t(already?'public.alreadyNamedBody':'public.successNamedBody',{name:company.company_name})}</p><Link className="primary-link full" to="/contacts">{t('public.viewContacts')}</Link></section></main>}
