const en = {
  common: { language:'Language', save:'Save', saving:'Saving…', cancel:'Cancel', close:'Close', edit:'Edit', delete:'Delete', deleting:'Deleting…', active:'Active', inactive:'Inactive', search:'Search', loading:'Loading…', logout:'Log out', loggingOut:'Signing out…', open:'Open', view:'View', status:'Status', actions:'Actions', email:'Email', phone:'Phone', website:'Website', address:'Address', username:'Username', password:'Password', fullName:'Full name', role:'Role', organizer:'Organizer', company:'Company', exhibitor:'Exhibitor', copied:'Copied', copyUrl:'Copy URL', tryAgain:'Try again', notProvided:'Not provided', error:'Something went wrong. Please try again.' },
  nav: { home:'Home', overview:'Overview', companies:'Companies', exhibitors:'Exhibitors', nfcTags:'NFC Tags', connections:'Connections', contacts:'Contacts', profile:'Profile', more:'More', admin:'Admin navigation', mobileAdmin:'Mobile admin navigation', exhibitor:'Exhibitor navigation', mobileExhibitor:'Mobile exhibitor navigation' },
  brand: { matching:'Business matching', organizer:'Event organizer', connected:'Event connected' },
  login: { headline:'Turn every tap into a meaningful connection.', intro:'Save the businesses you meet and keep every conversation within reach.', access:'Event access', welcome:'Welcome back', help:'Sign in to save and manage your business contacts.', returning:'After signing in, we’ll return you to the company profile.', identity:'Email or username', invalid:'Email/username or password is incorrect.', unavailable:'Sign in is unavailable right now. Please try again.', show:'Show', hide:'Hide', showPassword:'Show password', hidePassword:'Hide password', signIn:'Sign in', signingIn:'Signing in…', privacy:'Your session is protected and used only for this event.' },
  dashboard: { organizerOverview:'Organizer overview', eventDashboard:'Event dashboard', liveTotals:'Live participation and connection totals from the event.', recentConnections:'Recent connections', saved:'Saved', noConnections:'No connections yet', connectionsAppear:'New event connections will appear here.', yourNetwork:'Your network', savedContacts:'Saved contacts', browse:'Browse the companies you connected with.', searchContacts:'Search contacts', searchPlaceholder:'Search by company, industry, or country', loadingContacts:'Loading contacts…', noMatching:'No matching contacts', noSaved:'No saved contacts yet', tryDifferent:'Try a different company, industry, or country.', savedAppear:'Your saved company connections will appear here.', exhibitorHome:'Exhibitor home', welcome:'Welcome back, {name}', savedToday:'Saved today', eventNetwork:'Your event network', newConnections:'New connections', question:'What would you like to do?', review:'Review your network or open a company profile from an NFC tap.', viewContacts:'View contacts', howNfc:'How NFC connections work', latest:'Your latest saved companies', viewAll:'View all', loadingRecent:'Loading recent connections…', noRecent:'No recent connections', tapToStart:'Tap a company’s NFC profile and save it to start building your network.', atEvent:'At the event', saveFromTap:'Save a company from an NFC tap', step1:'Tap the company’s NFC tag with your phone.', step2:'Review the company profile that opens.', step3:'Choose Save contact to add it to your network.', businessContact:'Business contact', viewDetails:'View details', savedDate:'Saved {date}' },
  contacts: { details:'Contact details', profile:'Business profile', back:'← Back to contacts', loadError:'Unable to load this contact. It may no longer be available.', loading:'Loading contact…', about:'About', contactPerson:'Contact person', openWebsite:'Open website', savedAt:'Saved {date}' },
  profile: { accountEyebrow:'Your account', title:'Profile', logoutError:'Unable to sign out right now. Please try again.', account:'Account', managed:'Your profile is managed by the event organizer.' },
  companies: { title:'Companies', manage:'Manage participating businesses and their NFC profiles.', add:'Add company', edit:'Edit company', editAction:'Edit company', import:'Import CSV / Excel', search:'Search companies', searchPlaceholder:'Search by name or code', loading:'Loading companies…', noMatching:'No matching companies', none:'No companies yet', tryAnother:'Try another name or company code.', addFirst:'Add the first company to create its NFC profile.', companyName:'Company name', companyCode:'Company code', generated:'Company code (generated if blank)', industry:'Industry', country:'Country', contactName:'Contact name', contactPerson:'Contact person', contactPosition:'Contact position', logoUrl:'Company Logo URL', description:'Description', basic:'Basic information', contactInfo:'Contact information', details:'Company details', help:'Keep business and contact information accurate for the public NFC profile.', management:'Company management', loadingOne:'Loading company…', optionalLogo:'Optional · Use a direct image URL', preview:'Preview', isActive:'Company is active', save:'Save company', connections:'{count} connection(s)', deactivate:'Deactivate', deactivateConfirm:'Deactivate {name}?', clipboardError:'Clipboard access was unavailable. You can open and copy the URL manually.' },
  exhibitors: { title:'Exhibitors', create:'Create exhibitor', edit:'Edit exhibitor', created:'Exhibitor created.', updated:'Exhibitor updated.', newPassword:'Set New Password', active:'Exhibitor is active', cancelEdit:'Cancel edit', save:'Save exhibitor', deactivate:'Deactivate', activate:'Activate', connections:'Connections' },
  nfc: { title:'NFC Tags', intro:'Link physical tags to company profiles and manage their public URLs.', edit:'Edit NFC tag', create:'Create NFC tag', generatedUrl:'The generated URL can be written manually to a physical NFC tag.', tagCode:'Tag Code', selectCompany:'Select a company', tagActive:'Tag is active', regenerate:'Generate a new public token', save:'Save NFC tag', links:'Tag links', verify:'Open a URL to verify the same profile visitors receive from an NFC tap.', loading:'Loading NFC tags…', tag:'Tag', publicToken:'Public token', url:'NFC URL', copied:'URL copied.', none:'No NFC tags yet.', clipboardError:'Could not access the clipboard. Select and copy the URL manually.', deleted:'NFC tag {code} was deleted. Saved connections were preserved.', permanent:'Permanent action', deleteTitle:'Delete NFC tag?', deleteDescription:'{code} will stop opening its public company profile. Existing saved connections will be preserved.', deleteTag:'Delete tag', assignedNone:'No NFC tags assigned.' },
  connections: { title:'Connections', intro:'Connections saved by exhibitors during the event.', loading:'Loading connections…', none:'No connections yet', appear:'Saved business connections will appear here.', connected:'Connected', dateTime:'Date and time' },
  public: { loading:'Loading company information', unavailable:'This NFC profile isn’t available', loadFailed:'We couldn’t load this profile', inactive:'The tag may be inactive or its link may have expired. Ask an event organizer for help.', connectionHelp:'Check your connection and try again.', complete:'Connection complete', saved:'Contact saved', savedBody:'{name} is now in your business contacts.', viewContacts:'View my contacts', close:'You can safely close this page.', businessProfile:'Company Information', participant:'Event participant', visitWebsite:'Visit website', already:'Already connected', alreadyBody:'This company is already in your contacts.', question:'Save this business contact?', keep:'Keep the company details ready after the event.', saveError:'We couldn’t save this contact. Please try again.', saving:'Saving contact…', saveContact:'Save contact', signIn:'Sign in to save', later:'Maybe later', confirmHelp:'Nothing is saved until you confirm.' },
  import: { eyebrow:'Spreadsheet import', title:'Import companies', complete:'Import complete', created:'Created', updated:'Updated', skipped:'Skipped', view:'View companies', another:'Import another file', drop:'Drop a CSV or Excel file here', support:'Supported: .csv and .xlsx · Maximum 10 MB', browse:'Browse files', remove:'Remove', template:'Download CSV template', validating:'Validating…', preview:'Preview import', reading:'Reading and validating spreadsheet…', total:'Total rows', new:'New', updates:'Updates', invalid:'Invalid', ignored:'Ignored unmapped columns: {columns}', row:'Row', action:'Action', ready:'Ready', willChange:'{fields} will change', showing:'Showing the first 100 of {count} rows.', confirm:'Import {count} valid row(s)?', summary:'{newRows} will be created, {updateRows} updated, and {invalidRows} invalid row(s) skipped.', chooseAnother:'Choose another file', importing:'Importing…', submit:'Import companies', chooseFile:'Choose a file first.', invalidFile:'Choose a .csv or .xlsx file.', tooLarge:'The spreadsheet exceeds the 10 MB limit.' },
  session: { checking:'Checking your session…', logoutError:'Unable to sign out. Please try again.' },
  notFound: { title:'Page not found', body:'The page you’re looking for does not exist.', signIn:'Go to sign in' }
};

const th = {
  common:{language:'ภาษา',save:'บันทึก',saving:'กำลังบันทึก…',cancel:'ยกเลิก',close:'ปิด',edit:'แก้ไข',delete:'ลบ',deleting:'กำลังลบ…',active:'ใช้งาน',inactive:'ปิดใช้งาน',search:'ค้นหา',loading:'กำลังโหลด…',logout:'ออกจากระบบ',loggingOut:'กำลังออกจากระบบ…',open:'เปิด',view:'ดู',status:'สถานะ',actions:'การดำเนินการ',email:'อีเมล',phone:'โทรศัพท์',website:'เว็บไซต์',address:'ที่อยู่',username:'ชื่อผู้ใช้',password:'รหัสผ่าน',fullName:'ชื่อ-นามสกุล',role:'บทบาท',organizer:'ผู้จัดงาน',company:'บริษัท',exhibitor:'ผู้เข้าร่วมงาน',copied:'คัดลอกแล้ว',copyUrl:'คัดลอก URL',tryAgain:'ลองอีกครั้ง',notProvided:'ไม่ได้ระบุ',error:'เกิดข้อผิดพลาด โปรดลองอีกครั้ง'},
  nav:{home:'หน้าหลัก',overview:'ภาพรวม',companies:'บริษัท',exhibitors:'ผู้เข้าร่วมงาน',nfcTags:'แท็ก NFC',connections:'การเชื่อมต่อ',contacts:'รายชื่อผู้ติดต่อ',profile:'โปรไฟล์',more:'เพิ่มเติม',admin:'เมนูผู้ดูแลระบบ',mobileAdmin:'เมนูผู้ดูแลระบบบนมือถือ',exhibitor:'เมนูผู้เข้าร่วมงาน',mobileExhibitor:'เมนูผู้เข้าร่วมงานบนมือถือ'},
  login:{headline:'เปลี่ยนทุกการแตะให้เป็นการเชื่อมต่อที่มีความหมาย',intro:'บันทึกธุรกิจที่คุณพบและเก็บทุกบทสนทนาไว้ใกล้มือ',access:'เข้าสู่งาน',welcome:'ยินดีต้อนรับกลับ',help:'เข้าสู่ระบบเพื่อบันทึกและจัดการรายชื่อผู้ติดต่อทางธุรกิจ',returning:'หลังเข้าสู่ระบบ เราจะพาคุณกลับไปยังโปรไฟล์บริษัท',identity:'อีเมลหรือชื่อผู้ใช้',invalid:'อีเมล/ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',unavailable:'ไม่สามารถเข้าสู่ระบบได้ในขณะนี้ โปรดลองอีกครั้ง',show:'แสดง',hide:'ซ่อน',showPassword:'แสดงรหัสผ่าน',hidePassword:'ซ่อนรหัสผ่าน',signIn:'เข้าสู่ระบบ',signingIn:'กำลังเข้าสู่ระบบ…',privacy:'เซสชันของคุณได้รับการปกป้องและใช้สำหรับงานนี้เท่านั้น'},
  dashboard:{organizerOverview:'ภาพรวมผู้จัดงาน',eventDashboard:'แดชบอร์ดงาน',liveTotals:'ยอดผู้เข้าร่วมและการเชื่อมต่อล่าสุดภายในงาน',recentConnections:'การเชื่อมต่อล่าสุด',saved:'บันทึกเมื่อ',noConnections:'ยังไม่มีการเชื่อมต่อ',connectionsAppear:'การเชื่อมต่อใหม่จะแสดงที่นี่',yourNetwork:'เครือข่ายของคุณ',savedContacts:'รายชื่อที่บันทึกไว้',browse:'ดูบริษัทที่คุณเชื่อมต่อแล้ว',searchContacts:'ค้นหารายชื่อผู้ติดต่อ',searchPlaceholder:'ค้นหาตามบริษัท อุตสาหกรรม หรือประเทศ',loadingContacts:'กำลังโหลดรายชื่อผู้ติดต่อ…',noMatching:'ไม่พบรายชื่อที่ตรงกัน',noSaved:'ยังไม่มีรายชื่อที่บันทึกไว้',tryDifferent:'ลองค้นหาด้วยบริษัท อุตสาหกรรม หรือประเทศอื่น',savedAppear:'บริษัทที่บันทึกไว้จะแสดงที่นี่',exhibitorHome:'หน้าหลักผู้เข้าร่วมงาน',welcome:'ยินดีต้อนรับกลับ {name}',savedToday:'บันทึกวันนี้',eventNetwork:'เครือข่ายในงานของคุณ',newConnections:'การเชื่อมต่อใหม่',question:'คุณต้องการทำอะไร?',review:'ดูเครือข่ายของคุณหรือเปิดโปรไฟล์บริษัทจากการแตะ NFC',viewContacts:'ดูรายชื่อผู้ติดต่อ',howNfc:'การเชื่อมต่อ NFC ทำงานอย่างไร',latest:'บริษัทล่าสุดที่คุณบันทึก',viewAll:'ดูทั้งหมด',loadingRecent:'กำลังโหลดการเชื่อมต่อล่าสุด…',noRecent:'ยังไม่มีการเชื่อมต่อล่าสุด',tapToStart:'แตะโปรไฟล์ NFC ของบริษัทแล้วบันทึกเพื่อเริ่มสร้างเครือข่าย',atEvent:'ภายในงาน',saveFromTap:'บันทึกบริษัทด้วยการแตะ NFC',step1:'แตะแท็ก NFC ของบริษัทด้วยโทรศัพท์',step2:'ตรวจสอบโปรไฟล์บริษัทที่เปิดขึ้น',step3:'เลือกบันทึกรายชื่อเพื่อนำเข้าสู่เครือข่ายของคุณ',businessContact:'ผู้ติดต่อทางธุรกิจ',viewDetails:'ดูรายละเอียด',savedDate:'บันทึกเมื่อ {date}'},
  contacts:{details:'รายละเอียดผู้ติดต่อ',profile:'โปรไฟล์ธุรกิจ',back:'← กลับไปยังรายชื่อผู้ติดต่อ',loadError:'ไม่สามารถโหลดรายชื่อนี้ได้ อาจไม่มีข้อมูลแล้ว',loading:'กำลังโหลดผู้ติดต่อ…',about:'เกี่ยวกับบริษัท',contactPerson:'ผู้ติดต่อ',openWebsite:'เปิดเว็บไซต์',savedAt:'บันทึกเมื่อ {date}'},
  profile:{accountEyebrow:'บัญชีของคุณ',title:'โปรไฟล์',logoutError:'ไม่สามารถออกจากระบบได้ในขณะนี้ โปรดลองอีกครั้ง',account:'บัญชี',managed:'โปรไฟล์ของคุณจัดการโดยผู้จัดงาน'},
  companies:{title:'บริษัท',manage:'จัดการบริษัทที่เข้าร่วมและโปรไฟล์ NFC',add:'เพิ่มบริษัท',edit:'แก้ไขบริษัท',editAction:'แก้ไขบริษัท',import:'นำเข้า CSV / Excel',search:'ค้นหาบริษัท',searchPlaceholder:'ค้นหาตามชื่อหรือรหัส',loading:'กำลังโหลดบริษัท…',noMatching:'ไม่พบบริษัทที่ตรงกัน',none:'ยังไม่มีบริษัท',tryAnother:'ลองค้นหาด้วยชื่อหรือรหัสบริษัทอื่น',addFirst:'เพิ่มบริษัทแรกเพื่อสร้างโปรไฟล์ NFC',companyName:'ชื่อบริษัท',companyCode:'รหัสบริษัท',generated:'รหัสบริษัท (ระบบจะสร้างให้หากเว้นว่าง)',industry:'อุตสาหกรรม',country:'ประเทศ',contactName:'ชื่อผู้ติดต่อ',contactPerson:'ผู้ติดต่อ',contactPosition:'ตำแหน่งผู้ติดต่อ',logoUrl:'URL โลโก้บริษัท',description:'รายละเอียด',basic:'ข้อมูลพื้นฐาน',contactInfo:'ข้อมูลติดต่อ',details:'รายละเอียดบริษัท',help:'ดูแลข้อมูลธุรกิจและข้อมูลติดต่อให้ถูกต้องสำหรับโปรไฟล์ NFC สาธารณะ',management:'จัดการบริษัท',loadingOne:'กำลังโหลดบริษัท…',optionalLogo:'ไม่บังคับ · ใช้ URL รูปภาพโดยตรง',preview:'ตัวอย่าง',isActive:'บริษัทเปิดใช้งาน',save:'บันทึกบริษัท',connections:'{count} การเชื่อมต่อ',deactivate:'ปิดใช้งาน',deactivateConfirm:'ปิดใช้งาน {name}?',clipboardError:'ไม่สามารถเข้าถึงคลิปบอร์ดได้ คุณสามารถเปิดและคัดลอก URL เอง'},
  exhibitors:{title:'ผู้เข้าร่วมงาน',create:'สร้างผู้เข้าร่วมงาน',edit:'แก้ไขผู้เข้าร่วมงาน',created:'สร้างผู้เข้าร่วมงานแล้ว',updated:'อัปเดตผู้เข้าร่วมงานแล้ว',newPassword:'ตั้งรหัสผ่านใหม่',active:'ผู้เข้าร่วมงานเปิดใช้งาน',cancelEdit:'ยกเลิกการแก้ไข',save:'บันทึกผู้เข้าร่วมงาน',deactivate:'ปิดใช้งาน',activate:'เปิดใช้งาน',connections:'การเชื่อมต่อ'},
  nfc:{title:'แท็ก NFC',intro:'เชื่อมแท็กจริงกับโปรไฟล์บริษัทและจัดการ URL สาธารณะ',edit:'แก้ไขแท็ก NFC',create:'สร้างแท็ก NFC',generatedUrl:'สามารถเขียน URL ที่สร้างขึ้นลงในแท็ก NFC ได้',tagCode:'รหัสแท็ก',selectCompany:'เลือกบริษัท',tagActive:'แท็กเปิดใช้งาน',regenerate:'สร้างโทเค็นสาธารณะใหม่',save:'บันทึกแท็ก NFC',links:'ลิงก์แท็ก',verify:'เปิด URL เพื่อตรวจสอบโปรไฟล์เดียวกับที่ผู้เข้าชมเห็นเมื่อแตะ NFC',loading:'กำลังโหลดแท็ก NFC…',tag:'แท็ก',publicToken:'โทเค็นสาธารณะ',url:'URL ของ NFC',copied:'คัดลอก URL แล้ว',none:'ยังไม่มีแท็ก NFC',clipboardError:'ไม่สามารถเข้าถึงคลิปบอร์ดได้ โปรดเลือกและคัดลอก URL เอง',deleted:'ลบแท็ก NFC {code} แล้ว โดยยังเก็บการเชื่อมต่อเดิมไว้',permanent:'การดำเนินการถาวร',deleteTitle:'ลบแท็ก NFC?',deleteDescription:'{code} จะไม่สามารถเปิดโปรไฟล์บริษัทสาธารณะได้อีก โดยยังเก็บการเชื่อมต่อเดิมไว้',deleteTag:'ลบแท็ก',assignedNone:'ยังไม่ได้กำหนดแท็ก NFC'},
  connections:{title:'การเชื่อมต่อ',intro:'การเชื่อมต่อที่ผู้เข้าร่วมงานบันทึกไว้',loading:'กำลังโหลดการเชื่อมต่อ…',none:'ยังไม่มีการเชื่อมต่อ',appear:'การเชื่อมต่อทางธุรกิจที่บันทึกไว้จะแสดงที่นี่',connected:'เชื่อมต่อแล้ว',dateTime:'วันที่และเวลา'},
  public:{loading:'กำลังโหลดข้อมูลบริษัท',unavailable:'โปรไฟล์ NFC นี้ไม่พร้อมใช้งาน',loadFailed:'ไม่สามารถโหลดโปรไฟล์นี้ได้',inactive:'แท็กอาจปิดใช้งานหรือลิงก์หมดอายุ โปรดติดต่อผู้จัดงาน',connectionHelp:'ตรวจสอบการเชื่อมต่อแล้วลองอีกครั้ง',complete:'เชื่อมต่อสำเร็จ',saved:'บันทึกรายชื่อแล้ว',savedBody:'เพิ่ม {name} ในรายชื่อผู้ติดต่อทางธุรกิจของคุณแล้ว',viewContacts:'ดูรายชื่อผู้ติดต่อของฉัน',close:'คุณสามารถปิดหน้านี้ได้อย่างปลอดภัย',businessProfile:'ข้อมูลบริษัท',participant:'ผู้เข้าร่วมงาน',visitWebsite:'เยี่ยมชมเว็บไซต์',already:'เชื่อมต่อแล้ว',alreadyBody:'บริษัทนี้อยู่ในรายชื่อผู้ติดต่อของคุณแล้ว',question:'บันทึกผู้ติดต่อทางธุรกิจนี้?',keep:'เก็บรายละเอียดบริษัทไว้พร้อมใช้หลังจบงาน',saveError:'ไม่สามารถบันทึกผู้ติดต่อนี้ได้ โปรดลองอีกครั้ง',saving:'กำลังบันทึกผู้ติดต่อ…',saveContact:'บันทึกผู้ติดต่อ',signIn:'เข้าสู่ระบบเพื่อบันทึก',later:'ไว้ภายหลัง',confirmHelp:'จะยังไม่มีการบันทึกจนกว่าคุณจะยืนยัน'},
  session:{checking:'กำลังตรวจสอบเซสชัน…',logoutError:'ไม่สามารถออกจากระบบได้ โปรดลองอีกครั้ง'}, notFound:{title:'ไม่พบหน้า',body:'ไม่มีหน้าที่คุณกำลังค้นหา',signIn:'ไปยังหน้าเข้าสู่ระบบ'}
};

const ja = {
  common:{language:'言語',save:'保存',saving:'保存中…',cancel:'キャンセル',close:'閉じる',edit:'編集',delete:'削除',deleting:'削除中…',active:'有効',inactive:'無効',search:'検索',loading:'読み込み中…',logout:'ログアウト',loggingOut:'ログアウト中…',open:'開く',view:'表示',status:'ステータス',actions:'操作',email:'メール',phone:'電話',website:'ウェブサイト',address:'住所',username:'ユーザー名',password:'パスワード',fullName:'氏名',role:'役割',organizer:'主催者',company:'企業',exhibitor:'出展者',copied:'コピー済み',copyUrl:'URLをコピー',tryAgain:'再試行',notProvided:'未登録',error:'エラーが発生しました。もう一度お試しください。'},
  nav:{home:'ホーム',overview:'概要',companies:'企業',exhibitors:'出展者',nfcTags:'NFCタグ',connections:'コネクション',contacts:'連絡先',profile:'プロフィール',more:'その他',admin:'管理者ナビゲーション',mobileAdmin:'モバイル管理者ナビゲーション',exhibitor:'出展者ナビゲーション',mobileExhibitor:'モバイル出展者ナビゲーション'},
  login:{headline:'すべてのタップを価値あるつながりへ。',intro:'出会った企業を保存し、いつでも会話を振り返れます。',access:'イベントアクセス',welcome:'おかえりなさい',help:'ログインしてビジネスの連絡先を保存・管理します。',returning:'ログイン後、企業プロフィールに戻ります。',identity:'メールまたはユーザー名',invalid:'メール／ユーザー名またはパスワードが正しくありません。',unavailable:'現在ログインできません。もう一度お試しください。',show:'表示',hide:'非表示',showPassword:'パスワードを表示',hidePassword:'パスワードを非表示',signIn:'ログイン',signingIn:'ログイン中…',privacy:'セッションは保護され、このイベントのみに使用されます。'},
  dashboard:{organizerOverview:'主催者概要',eventDashboard:'イベントダッシュボード',liveTotals:'イベントの参加状況とコネクション数です。',recentConnections:'最近のコネクション',saved:'保存日時',noConnections:'コネクションはまだありません',connectionsAppear:'新しいコネクションがここに表示されます。',yourNetwork:'あなたのネットワーク',savedContacts:'保存済み連絡先',browse:'つながった企業を確認できます。',searchContacts:'連絡先を検索',searchPlaceholder:'企業・業種・国で検索',loadingContacts:'連絡先を読み込み中…',noMatching:'一致する連絡先がありません',noSaved:'保存済みの連絡先はまだありません',tryDifferent:'別の企業名、業種、国で検索してください。',savedAppear:'保存した企業がここに表示されます。',exhibitorHome:'出展者ホーム',welcome:'おかえりなさい、{name}さん',savedToday:'本日の保存数',eventNetwork:'イベントのネットワーク',newConnections:'新しいコネクション',question:'何をしますか？',review:'ネットワークを確認するか、NFCタップから企業プロフィールを開きます。',viewContacts:'連絡先を見る',howNfc:'NFCコネクションの仕組み',latest:'最近保存した企業',viewAll:'すべて表示',loadingRecent:'最近のコネクションを読み込み中…',noRecent:'最近のコネクションはありません',tapToStart:'企業のNFCプロフィールをタップして保存し、ネットワークを作りましょう。',atEvent:'イベント会場で',saveFromTap:'NFCタップで企業を保存',step1:'スマートフォンで企業のNFCタグをタップします。',step2:'開いた企業プロフィールを確認します。',step3:'「連絡先を保存」を選び、ネットワークに追加します。',businessContact:'ビジネス連絡先',viewDetails:'詳細を見る',savedDate:'保存日時：{date}'},
  contacts:{details:'連絡先の詳細',profile:'企業プロフィール',back:'← 連絡先に戻る',loadError:'この連絡先を読み込めません。利用できなくなった可能性があります。',loading:'連絡先を読み込み中…',about:'企業について',contactPerson:'担当者',openWebsite:'ウェブサイトを開く',savedAt:'保存日時：{date}'},
  profile:{accountEyebrow:'アカウント',title:'プロフィール',logoutError:'現在ログアウトできません。もう一度お試しください。',account:'アカウント',managed:'プロフィールはイベント主催者が管理しています。'},
  companies:{title:'企業',manage:'参加企業とNFCプロフィールを管理します。',add:'企業を追加',edit:'企業を編集',editAction:'企業を編集',import:'CSV / Excelをインポート',search:'企業を検索',searchPlaceholder:'企業名またはコードで検索',loading:'企業を読み込み中…',noMatching:'一致する企業がありません',none:'企業はまだありません',tryAnother:'別の企業名またはコードをお試しください。',addFirst:'最初の企業を追加してNFCプロフィールを作成します。',companyName:'企業名',companyCode:'企業コード',generated:'企業コード（空欄の場合は自動生成）',industry:'業種',country:'国',contactName:'担当者名',contactPerson:'担当者',contactPosition:'役職',logoUrl:'企業ロゴURL',description:'説明',basic:'基本情報',contactInfo:'連絡先情報',details:'企業情報',help:'公開NFCプロフィールの企業・連絡先情報を正確に保ちます。',management:'企業管理',loadingOne:'企業を読み込み中…',optionalLogo:'任意 · 画像の直接URLを使用',preview:'プレビュー',isActive:'企業を有効にする',save:'企業を保存',connections:'{count}件のコネクション',deactivate:'無効化',deactivateConfirm:'{name}を無効にしますか？',clipboardError:'クリップボードにアクセスできません。URLを開いて手動でコピーしてください。'},
  exhibitors:{title:'出展者',create:'出展者を作成',edit:'出展者を編集',created:'出展者を作成しました。',updated:'出展者を更新しました。',newPassword:'新しいパスワードを設定',active:'出展者を有効にする',cancelEdit:'編集をキャンセル',save:'出展者を保存',deactivate:'無効化',activate:'有効化',connections:'コネクション'},
  nfc:{title:'NFCタグ',intro:'物理タグを企業プロフィールにリンクし、公開URLを管理します。',edit:'NFCタグを編集',create:'NFCタグを作成',generatedUrl:'生成されたURLを物理NFCタグに書き込めます。',tagCode:'タグコード',selectCompany:'企業を選択',tagActive:'タグを有効にする',regenerate:'新しい公開トークンを生成',save:'NFCタグを保存',links:'タグリンク',verify:'URLを開き、NFCタップ時と同じプロフィールを確認します。',loading:'NFCタグを読み込み中…',tag:'タグ',publicToken:'公開トークン',url:'NFC URL',copied:'URLをコピーしました。',none:'NFCタグはまだありません。',clipboardError:'クリップボードにアクセスできません。URLを選択して手動でコピーしてください。',deleted:'NFCタグ {code} を削除しました。保存済みコネクションは保持されています。',permanent:'取り消せない操作',deleteTitle:'NFCタグを削除しますか？',deleteDescription:'{code} では公開企業プロフィールを開けなくなります。保存済みコネクションは保持されます。',deleteTag:'タグを削除',assignedNone:'NFCタグが割り当てられていません。'},
  connections:{title:'コネクション',intro:'イベント中に出展者が保存したコネクションです。',loading:'コネクションを読み込み中…',none:'コネクションはまだありません',appear:'保存されたビジネスコネクションがここに表示されます。',connected:'接続済み',dateTime:'日時'},
  public:{loading:'企業情報を読み込み中',unavailable:'このNFCプロフィールは利用できません',loadFailed:'プロフィールを読み込めませんでした',inactive:'タグが無効か、リンクの有効期限が切れている可能性があります。主催者にお問い合わせください。',connectionHelp:'接続を確認して、もう一度お試しください。',complete:'接続完了',saved:'連絡先を保存しました',savedBody:'{name}をビジネス連絡先に追加しました。',viewContacts:'連絡先を見る',close:'このページは安全に閉じられます。',businessProfile:'企業情報',participant:'イベント参加企業',visitWebsite:'ウェブサイトを見る',already:'接続済み',alreadyBody:'この企業はすでに連絡先に保存されています。',question:'このビジネス連絡先を保存しますか？',keep:'イベント後も企業情報をすぐ確認できます。',saveError:'この連絡先を保存できませんでした。もう一度お試しください。',saving:'連絡先を保存中…',saveContact:'連絡先を保存',signIn:'ログインして保存',later:'後で',confirmHelp:'確認するまで保存されません。'},
  session:{checking:'セッションを確認中…',logoutError:'ログアウトできませんでした。もう一度お試しください。'}, notFound:{title:'ページが見つかりません',body:'お探しのページは存在しません。',signIn:'ログインへ'}
};

th.brand={matching:'การจับคู่ธุรกิจ',organizer:'ผู้จัดงาน',connected:'เชื่อมต่อกับงานแล้ว'};
ja.brand={matching:'ビジネスマッチング',organizer:'イベント主催者',connected:'イベント接続済み'};
th.import={eyebrow:'นำเข้าตารางข้อมูล',title:'นำเข้าบริษัท',complete:'นำเข้าเสร็จสมบูรณ์',created:'สร้างแล้ว',updated:'อัปเดตแล้ว',skipped:'ข้าม',view:'ดูบริษัท',another:'นำเข้าไฟล์อื่น',drop:'วางไฟล์ CSV หรือ Excel ที่นี่',support:'รองรับ .csv และ .xlsx · สูงสุด 10 MB',browse:'เลือกไฟล์',remove:'นำออก',template:'ดาวน์โหลดเทมเพลต CSV',validating:'กำลังตรวจสอบ…',preview:'ดูตัวอย่างการนำเข้า',reading:'กำลังอ่านและตรวจสอบตาราง…',total:'แถวทั้งหมด',new:'ใหม่',updates:'อัปเดต',invalid:'ไม่ถูกต้อง',ignored:'คอลัมน์ที่ไม่ได้นำเข้า: {columns}',row:'แถว',action:'การดำเนินการ',ready:'พร้อม',willChange:'{fields} จะเปลี่ยนแปลง',showing:'แสดง 100 แถวแรกจาก {count} แถว',confirm:'นำเข้า {count} แถวที่ถูกต้อง?',summary:'จะสร้าง {newRows} แถว อัปเดต {updateRows} แถว และข้าม {invalidRows} แถวที่ไม่ถูกต้อง',chooseAnother:'เลือกไฟล์อื่น',importing:'กำลังนำเข้า…',submit:'นำเข้าบริษัท',chooseFile:'โปรดเลือกไฟล์ก่อน',invalidFile:'โปรดเลือกไฟล์ .csv หรือ .xlsx',tooLarge:'ตารางมีขนาดเกิน 10 MB'};
ja.import={eyebrow:'スプレッドシート取込',title:'企業をインポート',complete:'インポート完了',created:'作成',updated:'更新',skipped:'スキップ',view:'企業を見る',another:'別のファイルをインポート',drop:'CSVまたはExcelファイルをここにドロップ',support:'対応形式：.csv、.xlsx · 最大10 MB',browse:'ファイルを選択',remove:'削除',template:'CSVテンプレートをダウンロード',validating:'検証中…',preview:'インポートをプレビュー',reading:'スプレッドシートを読み込み・検証中…',total:'全行',new:'新規',updates:'更新',invalid:'無効',ignored:'未対応の列を無視しました：{columns}',row:'行',action:'操作',ready:'準備完了',willChange:'{fields} を変更します',showing:'{count}行中、最初の100行を表示しています。',confirm:'有効な{count}行をインポートしますか？',summary:'{newRows}行を作成、{updateRows}行を更新し、無効な{invalidRows}行をスキップします。',chooseAnother:'別のファイルを選択',importing:'インポート中…',submit:'企業をインポート',chooseFile:'先にファイルを選択してください。',invalidFile:'.csvまたは.xlsxファイルを選択してください。',tooLarge:'スプレッドシートが10 MBを超えています。'};
export const translations = { en, th, ja };
